### ISSUE TITLE
how i install aircrack-ng?

### ISSUE THREAD

**Issue by XandeDosBans** [3xploitGuy/lazyaircrack#4]
i installed all the code and it run, but when i choose one of the options only appear that have lines missing and anything its make
(and sorry by any error, my english insn't the best :c)

**Comment by 3xploitGuy** [comment]
Hi @XandeDosBans , the script takes care of it's dependencies, you don't need to install it explicitly but the command for it is **apt install aircrack-ng** , try to use GitHub Discussions for doubts and queries [[click here](https://github.com/3xploitGuy/lazyaircrack/discussions)].
Thank You.
